<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe item batch-edit');
?>

<?php echo $this->pageTitle($dataset->name(), 1, $this->translate('DataScribe: Dataset'), $this->translate('Batch edit items')); ?>

<?php echo $this->form()->openTag($form); ?>

<?php foreach ($items as $item): ?>
<input type="hidden" name="item_ids[]" value="<?php echo $item->id(); ?>">
<?php endforeach; ?>

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url('admin/datascribe-item', ['action' => 'browse'], true), ['class' => 'button']); ?>
    <input type="submit" name="batch_edit" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>">
</div>

<?php echo $this->formCollection($form, false); ?>

<?php echo $this->form()->closeTag(); ?>

<div class="sidebar always-open">
    <button type="button" class="sidebar-drawer collapse" aria-label="<?php echo $this->translate('Collapse'); ?>"></button>
    <h3><?php echo $this->translate('Affected items'); ?></h3>
    <p><?php echo sprintf($this->translate('You are editing the following %s items'), count($items)); ?></p>
    <ul class="batch-selected">
        <?php foreach ($items as $item): ?>
        <li><?php echo $item->link($item->item()->displayTitle(), null, ['target' => '_blank']); ?></li>
        <?php endforeach; ?>
    </ul>
</div>
