<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe item batch-edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/admin.css', 'Datascribe'));
$this->headScript()->appendFile($this->assetUrl('js/admin.js', 'Datascribe'));
?>

<?php echo $this->pageTitle($dataset->name(), 1, $this->translate('DataScribe: Dataset'), $this->translate('Batch edit all items')); ?>

<?php echo $this->form()->openTag($form); ?>

<input type="hidden" name="query" value="<?php echo $this->escapeHtml(json_encode($query)); ?>">

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url('admin/datascribe-item', ['action' => 'browse'], true), ['class' => 'button']); ?>
    <input type="submit" name="batch_edit" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>">
</div>

<?php echo $this->formCollection($form, false); ?>

<?php echo $this->form()->closeTag(); ?>

<div class="sidebar always-open">
    <button type="button" class="sidebar-drawer collapse" aria-label="<?php echo $this->translate('Collapse'); ?>"></button>
    <h3><?php echo $this->translate('Affected items'); ?></h3>
    <p><?php echo sprintf($this->translate('You are editing %s items'), $this->hyperlink(number_format($count), $this->url(null, ['action' => 'browse'], ['query' => $query], true), ['target' => '_blank'])); ?></p>
</div>
