<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe item browse');
?>

<?php echo $this->pageTitle($dataset->name(), 1, $this->translate('DataScribe: Dataset'), $this->translate('Browse')); ?>

<?php
if ($dataset->userIsAllowed('update')):
?>
<div id="page-actions">
    <div id="page-action-menu">
        <a href="#" class="expand button" aria-label="<?php echo $this->translate('Expand'); ?>"><?php echo $this->translate('Actions'); ?></a>
        <ul class="collapsible">
            <li><?php echo $dataset->link($this->translate('Edit dataset'), 'edit'); ?></li>
            <li><a href="#" class="sidebar-content" data-sidebar-selector="#sync-dataset"><?php echo $this->translate('Sync dataset'); ?></a></li>
        </ul>
    </div>
</div>
<?php endif; ?>

<?php echo $this->datascribe()->breadcrumbs(); ?>

<div class="browse-controls">
    <?php echo sprintf(
        '<form id="datascribe-search"><input type="text" name="search" value="%s" aria-label="%s"><button type="submit" aria-label="%s" class="o-icon-search"></button></form>',
        $this->escapeHtml($this->params()->fromQuery('search')),
        $this->translate('Query'),
        $this->translate('Search')
    ); ?>
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector([
        [
            'label' => $this->translate('Date synced'),
            'value' => 'synced'
        ],
    ]); ?>
</div>

<?php if ($items): ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Item'); ?></th>
            <th><?php echo $this->translate('Date synced'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($items as $item): ?>
        <tr>
            <td>
                <?php echo $item->linkPretty(); ?>
                <ul class="actions">
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-content-url' => $item->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'data-sidebar-selector' => '#show-details',
                        'title' => $this->translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?php echo $this->i18n()->dateFormat($item->synced()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<?php else: ?>
<div class="no-resources">
    <p>
        <?php echo $this->translate('No items found'); ?>
        <br>
        <?php echo $this->translate('Do you need to sync the dataset? If you have recently synced, the sync job has likely not finished.'); ?>
    </p>
</div>
<?php endif; ?>

<div id="dataset-metadata" class="sidebar always-open">
    <?php echo $this->partial('datascribe/admin/dataset/show-details') ?>
</div>

<div id="show-details" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<div id="sync-dataset" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Sync dataset'); ?></h3>
    <?php if (!$dataset->itemSet()): ?>
    <p class="error"><?php echo $this->translate('This dataset has no item set. Set an item set to enable syncing.'); ?></p>
    <?php endif; ?>
    <p><?php echo $this->translate('Synchronize this dataset with the configured item set. Once synchronized, this dataset will contain every item in the item set. You should synchronize periodically, any time items are added or removed from the item set.'); ?></p>
    <?php
    $syncForm->setAttribute('action', $this->url('admin/datascribe-dataset-id', ['action' => 'sync'], true));
    echo $this->form($syncForm);
    ?>
</div>
