<?php
$this->headLink()->prependStylesheet($this->assetUrl('css/advanced-search.css', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'datascribe item search');

$query = $this->params()->fromQuery();
$reviewStatus = isset($query['review_status']) ? $query['review_status'] : null;
$lockedById = isset($query['locked_by_id']) ? $query['locked_by_id'] : null;
$submittedById = isset($query['submitted_by_id']) ? $query['submitted_by_id'] : null;
$reviewedById = isset($query['reviewed_by_id']) ? $query['reviewed_by_id'] : null;
?>

<?php echo $this->pageTitle($dataset->name(), 1, $this->translate('DataScribe: Dataset'), $this->translate('Search')); ?>

<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
    <div id="page-actions">
        <?php echo $this->hyperlink($this->translate('Reset'), $this->url(null, [], true), ['class' => 'button']); ?>
        <?php echo $this->cancelButton(); ?>
        <input type="submit" name="submit" value="<?php echo $this->escapeHtml($this->translate('Search')); ?>">
    </div>
    <?php echo $this->datascribe()->itemReviewStatusSelect($project->id(), 'review_status', $reviewStatus, $this->translate('Review status')); ?>
    <?php echo $this->datascribe()->itemLockedBySelect($project->id(), 'locked_by_id', $lockedById, $this->translate('Locked by user')); ?>
    <?php echo $this->datascribe()->itemSubmittedBySelect($project->id(), 'submitted_by_id', $submittedById, $this->translate('Submitted by user')); ?>
    <?php echo $this->datascribe()->itemReviewedBySelect($project->id(), 'reviewed_by_id', $reviewedById, $this->translate('Reviewed by user')); ?>
    <?php echo $this->partial('common/advanced-search/resource-class', ['query' => $query]); ?>
    <?php echo $this->partial('common/advanced-search/resource-template', ['query' => $query]); ?>
</form>
