<?php
$this->headLink()->prependStylesheet($this->assetUrl('css/advanced-search.css', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'datascribe item search');
$form->setAttribute('id', 'advanced-search');
?>

<?php echo $this->pageTitle($dataset->name(), 1, $this->translate('DataScribe: Dataset'), $this->translate('Search')); ?>

<?php echo $this->form()->openTag($form); ?>
    <div id="page-actions">
        <?php echo $this->hyperlink($this->translate('Reset'), $this->url(null, [], true), ['class' => 'button']); ?>
        <?php echo $this->hyperlink($this->translate('Cancel'), $this->url('admin/datascribe-item', ['action' => 'browse'], true), ['class' => 'button']); ?>
        <input type="submit" name="submit" value="<?php echo $this->escapeHtml($this->translate('Search')); ?>">
    </div>
    <?php echo $this->formCollection($form, false); ?>
    <?php echo $this->partial('common/advanced-search.phtml', [
        'query' => $this->params()->fromQuery(),
        'partialExcludelist' => [
            'common/advanced-search/owner',
            'common/advanced-search/sort',
            'common/advanced-search/site',
        ],
    ]); ?>
<?php echo $this->form()->closeTag(); ?>
