<h3><?php echo $this->translate('Item metadata'); ?></h3>
<div class="meta-group">
    <h4><?php echo $this->translate('Item #'); ?></h4>
    <div class="value"><?php echo $item->id(); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('DataScribe item'); ?></h4>
    <div class="value"><?php echo $item->linkPretty(); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Omeka item'); ?></h4>
    <div class="value"><?php echo $oItem->linkPretty(); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Dataset'); ?></h4>
    <div class="value"><?php echo $dataset->link($dataset->name()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Project'); ?></h4>
    <div class="value"><?php echo $project->link($project->name()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Status'); ?></h4>
    <div class="value"><?php echo $this->translate($item->statusLabel()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Record count'); ?></h4>
    <div class="value"><?php echo number_format($item->recordCount()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Last submitted'); ?></h4>
    <?php
    $submitted = $item->submitted();
    $submittedBy = $item->submittedBy();
    ?>
    <div class="value"><?php
    echo $submitted
        ? sprintf(
            '%s by %s',
            $this->i18n()->dateFormat($submitted, 'medium', 'medium'),
            null === $submittedBy
                ? $this->translate('[Unknown]')
                : $submittedBy->link($submittedBy->name())
        ) : $this->translate('Not submitted');
    ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Last reviewed'); ?></h4>
    <?php
    $reviewed = $item->reviewed();
    $reviewedBy = $item->reviewedBy();
    ?>
    <div class="value"><?php
    echo $reviewed
        ? sprintf(
            '%s by %s',
            $this->i18n()->dateFormat($reviewed, 'medium', 'medium'),
            null === $reviewedBy
                ? $this->translate('[Unknown]')
                : $reviewedBy->link($reviewedBy->name())
        ) : $this->translate('Not reviewed');
    ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Last locked'); ?></h4>
    <?php
    $locked = $item->locked();
    $lockedBy = $item->lockedBy();
    ?>
    <div class="value"><?php
    echo $locked
        ? sprintf(
            '%s by %s',
            $this->i18n()->dateFormat($locked, 'medium', 'medium'),
            null === $lockedBy
                ? $this->translate('[Unknown]')
                : $lockedBy->link($lockedBy->name())
        ) : $this->translate('Unlocked');
    ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Transcriber notes'); ?></h4>
    <div class="value"><?php echo nl2br($item->transcriberNotes()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Reviewer notes'); ?></h4>
    <div class="value"><?php echo nl2br($item->reviewerNotes()); ?></div>
</div>
