<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe record add');
$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formElement($form->get('recordform_csrf')); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Add'); ?></button>
</div>
<?php echo $this->formRow($form->get('o-module-datascribe:needs_review')); ?>
<?php echo $this->formRow($form->get('o-module-datascribe:needs_work')); ?>
<?php echo $this->formRow($form->get('o-module-datascribe:transcriber_notes')); ?>
<?php echo $this->formRow($form->get('o-module-datascribe:reviewer_notes')); ?>
<?php echo $this->formCollection($form->get('o-module-datascribe:value'), false); ?>
<?php echo $this->form()->closeTag(); ?>
