<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe record add');
$this->headLink()->appendStylesheet('https://cdn.jsdelivr.net/npm/tablesaw@3.1.2/dist/tablesaw.css');
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/tablesaw@3.1.2/dist/tablesaw.jquery.js');
$this->headScript()->appendFile($this->assetUrl('js/admin/record-form.js', 'Datascribe'));
$form->prepare();
$fieldsets = $form->get('o-module-datascribe:value')->getFieldsets();
?>

<?php echo $this->pageTitle($item->item()->title(), 1, $this->translate('DataScribe: Item'), $this->translate('New record')); ?>

<?php echo $this->partial('before-after-records', ['dataset' => $dataset, 'records' => $recordsBefore, 'beforeAfter' => null]); ?>

<div class="current-row horizontal">

<div class="row-controls">
    <button type="button" class="full-screen"><?php echo $this->translate('Focus mode'); ?></button>
    <div class="layout">
        <label><?php echo $this->translate('Layout'); ?></label>
        <button type="button" name="horizontal" class="horizontal active" aria-label="<?php echo $this->escapeHtml($this->translate('Horizontal view')); ?>" title="<?php echo $this->escapeHtml($this->translate('Horizontal view')); ?>" disabled=""></button>
        <button type="button" name="vertical" class="vertical" aria-label="<?php echo $this->escapeHtml($this->translate('Vertical view')); ?>" title="<?php echo $this->escapeHtml($this->translate('Vertical view')); ?>"></button>
    </div>
</div>

<?php echo $this->partial('media-viewer', ['oItem' => $oItem]); ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formElement($form->get('csrf')); ?>

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url(null, ['action' => 'browse'], true), ['class' => 'button']); ?>
    <input type="submit" name="submit-add-another" class="button" value="<?php echo $this->escapeHtml($this->translate('Add +')); ?>">
    <input type="submit" name="submit" value="<?php echo $this->escapeHtml($this->translate('Add')); ?>">
</div>
<?php if ($fieldsets): ?>
<?php foreach ($fieldsets as $fieldset): ?>
<?php $field = $fieldset->getOption('datascribe_field'); ?>
<fieldset>
    <?php echo sprintf('<legend>%s</legend>', $field->name()); ?>
    <?php if ($fieldDescription = $field->description()): ?>
    <?php echo sprintf('<p>%s</p>', $fieldDescription); ?>
    <?php endif; ?>
    <?php if ($field->isRequired()): ?>
    <?php echo sprintf('<p class="warning">%s</p>', $this->translate('This field is required. The value will be marked as invalid if not completed.')); ?>
    <?php endif; ?>
    <?php if ($field->dataTypeIsUnknown()): ?>
    <?php echo sprintf('<p class="error">%s</p>', $this->translate('This field\'s data type is unknown. The value cannot be added.')); ?>
    <?php endif; ?>
    <?php echo $this->formCollection($fieldset->get('data'), false); ?>
    <div class="common-elements">
        <label><?php echo $this->translate('Is missing'); ?><?php echo $this->formElement($fieldset->get('is_missing')); ?></label>
        <label><?php echo $this->translate('Is illegible'); ?><?php echo $this->formElement($fieldset->get('is_illegible')); ?></label>
        <?php echo $this->formElement($fieldset->get('set_null')); ?>
    </div>
    <button type="button" class="set-null-button" aria-label="<?php echo $this->escapeHtml($this->translate('Reset value')); ?>" title="<?php echo $this->escapeHtml($this->translate('Reset value')); ?>"></button>
</fieldset>
<?php endforeach; ?>
<?php else: ?>
<div class="no-resources">
    <?php if ($this->userIsAllowed('Datascribe\Api\Adapter\DatascribeDatasetAdapter', 'create')): ?>
    <p><?php echo sprintf(
        $this->translate('This dataset has no form. %s'),
        $this->hyperlink($this->translate('Build the form.'), $this->url('admin/datascribe-dataset-id', ['action' => 'edit', 'project-id' => $project->id(), 'dataset-id' => $dataset->id()], ['fragment' => 'form-builder']))
    ); ?></p>
    <?php else: ?>
    <p><?php echo $this->translate('This dataset has no form.'); ?></p>
    <?php endif; ?>
</div>
<?php endif; ?>

<div class="sidebar always-open">
    <button type="button" class="sidebar-drawer collapse" aria-label="<?php echo $this->translate('Collapse'); ?>"></button>
    <div class="meta-group">
        <input type="submit" name="submit-save-progress"  class="button" value="<?php echo $this->escapeHtml($this->translate('Save progress')); ?>">
    </div>
    <h3><?php echo $this->translate('Record actions'); ?></h3>
    <?php if ($form->has('o-module-datascribe:needs_review')): ?>
    <div class="meta-group checkbox">
        <h4><?php echo $this->translate('Needs review'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:needs_review')); ?></div>
    </div>
    <?php endif; ?>
    <?php if ($form->has('o-module-datascribe:needs_work')): ?>
    <div class="meta-group checkbox">
        <h4><?php echo $this->translate('Needs work'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:needs_work')); ?></div>
    </div>
    <?php endif; ?>
    <?php if ($form->has('o-module-datascribe:transcriber_notes')): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Transcriber notes'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:transcriber_notes')); ?></div>
    </div>
    <?php endif; ?>
    <?php if ($form->has('o-module-datascribe:reviewer_notes')): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Reviewer notes'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:reviewer_notes')); ?></div>
    </div>
    <?php endif; ?>
</div>

<?php echo $this->form()->closeTag(); ?>
</div>
