<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe record add');
$this->headLink()->appendStylesheet('https://cdn.jsdelivr.net/npm/tablesaw@3.1.2/dist/tablesaw.css');
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/tablesaw@3.1.2/dist/tablesaw.jquery.js');
$this->headScript()->appendFile($this->assetUrl('js/admin/record-form.js', 'Datascribe'));
$form->prepare();
$fieldsets = $form->get('o-module-datascribe:value')->getFieldsets();
?>
<?php echo $this->pageTitle($item->item()->title(), 1, $this->translate('DataScribe: Item'), $this->translate('New record')); ?>
<div class="rows">
    <?php echo $this->partial('previous-next-records', ['dataset' => $dataset, 'records' => $recordsPrevious, 'heading' => $this->translate('Previous records'), 'previousNext' => 'previous']); ?>
    <div class="current-row horizontal">
        <?php echo $this->partial('form/row-controls'); ?>
        <?php echo $this->partial('form/media-viewer'); ?>
        <?php echo $this->form()->openTag($form); ?>
            <?php echo $this->formElement($form->get('csrf')); ?>
            <div id="page-actions">
                <?php echo $this->hyperlink($this->translate('Cancel'), $this->url(null, ['action' => 'browse'], true), ['class' => 'button']); ?>
                <input type="submit" name="submit-add-another" class="button" value="<?php echo $this->escapeHtml($this->translate('Add +')); ?>">
                <input type="submit" name="submit" value="<?php echo $this->escapeHtml($this->translate('Add')); ?>">
            </div>
            <?php if ($fieldsets): ?>
            <?php foreach ($fieldsets as $fieldset): ?>
            <?php
            $field = $fieldset->getOption('datascribe_field');
            ?>
            <fieldset>
                <?php echo sprintf('<legend>%s</legend>', $field->name()); ?>
                <?php if ($fieldDescription = $field->description()): ?>
                <?php echo sprintf('<p class="description">%s</p>', $fieldDescription); ?>
                <?php endif; ?>
                <?php if ($field->isRequired()): ?>
                <?php echo sprintf('<p class="warning">%s</p>', $this->translate('This field is required. The value will be marked as invalid if not completed.')); ?>
                <?php endif; ?>
                <?php if ($field->dataTypeIsUnknown()): ?>
                <?php echo sprintf('<p class="error">%s</p>', $this->translate('This field\'s data type is unknown. The value cannot be added.')); ?>
                <?php endif; ?>
                <div class="value-elements">
                    <?php echo $this->formCollection($fieldset->get('data'), false); ?>
                </div>
                <div class="common-elements">
                    <label><?php echo $this->translate('Is missing'); ?><?php echo $this->formElement($fieldset->get('is_missing')); ?></label>
                    <label><?php echo $this->translate('Is illegible'); ?><?php echo $this->formElement($fieldset->get('is_illegible')); ?></label>
                    <label class="set-null-checkbox"><?php echo $this->translate('Reset value'); ?><?php echo $this->formElement($fieldset->get('set_null')); ?></label>
                </div>
            </fieldset>
            <?php endforeach; ?>
            <?php else: ?>
            <?php echo $this->partial('form/no-resources'); ?>
            <?php endif; ?>
            <?php echo $this->partial('form/sidebar', ['action' => 'add', 'form' => $form, 'record' => null]); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <?php echo $this->partial('form/guidelines'); ?>
</div>
