<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe record batch-edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/admin.css', 'Datascribe'));
$this->headScript()->appendFile($this->assetUrl('js/admin.js', 'Datascribe'));
$form->prepare();
?>

<?php echo $this->pageTitle($item->item()->title(), 1, $this->translate('DataScribe: Item'), $this->translate('Batch edit all records')); ?>

<?php echo $this->form()->openTag($form); ?>

<input type="hidden" name="query" value="<?php echo $this->escapeHtml(json_encode($query)); ?>">

<div id="page-actions">
    <?php echo $this->cancelButton(); ?>
    <input type="submit" name="batch_edit" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>">
</div>

<?php echo $this->formCollection($form); ?>

<?php echo $this->form()->closeTag(); ?>

<div class="sidebar always-open">
    <button type="button" class="sidebar-drawer collapse" aria-label="<?php echo $this->translate('Collapse'); ?>"></button>
    <h3><?php echo $this->translate('Affected records'); ?></h3>
    <p><?php echo sprintf($this->translate('You are editing %s records'), $this->hyperlink(number_format($count), $this->url(null, ['action' => 'browse'], ['query' => $query], true), ['target' => '_blank'])); ?></p>
</div>
