<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe record browse');
$this->headLink()->appendStylesheet($this->assetUrl('css/admin.css', 'Datascribe'));
$this->headScript()->appendFile($this->assetUrl('js/admin.js', 'Datascribe'));
$canViewBatchUpdate = $dataset->userIsAllowed('view_datascribe_item_batch_update');
$filters = [
    [
        'label' => $this->translate('Needs review'),
        'value' => 'needs_review'
    ],
    [
        'label' => $this->translate('Needs work'),
        'value' => 'needs_work'
    ],
];
$sortBy = [
    [
        'label' => $this->translate('Created'),
        'value' => 'created'
    ],
];
?>

<?php echo $this->pageTitle($oItem->title(), 1, $this->translate('DataScribe: Item'), $this->translate('Browse')); ?>

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Add new record'), $this->url(null, ['action' => 'add'], true), ['class' => 'button']); ?>
    <button><?php echo $this->translate('Save'); ?></button>
</div>

<?php echo $this->datascribe()->breadcrumbs(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->hyperlink($this->translate('Advanced search'), $this->url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true)); ?>
    <?php echo $this->sortSelector($sortBy); ?>
    <?php echo $this->filterSelector($filters); ?>
</div>

<?php if ($records): ?>

<form method="post" id="batch-form">

<?php if ($canViewBatchUpdate): ?>
<div class="batch-inputs">
    <select class="batch-actions-select" aria-label="<?php echo $this->translate('Batch actions'); ?>">
        <option value="default"><?php echo $this->translate('Batch actions'); ?></option>
        <option value="update-selected" disabled="true"><?php echo $this->translate('Edit selected'); ?></option>
        <option value="update-all"><?php echo $this->translate('Edit all'); ?></option>
    </select>
    <div class="batch-actions">
        <button type="button" class="default active" disabled="true"><?php echo $this->translate('Go'); ?></button>
        <input type="submit" class="update-selected" name="update_selected" value="<?php echo $this->translate('Go'); ?>" formaction="<?php echo $this->escapeHtml($this->url(null, ['action' => 'batch-edit'], true)); ?>">
        <input type="submit" class="update-all" name="update_all" value="<?php echo $this->translate('Go'); ?>" formaction="<?php echo $this->escapeHtml($this->url(null, ['action' => 'batch-edit-all'], true)); ?>">
        <input type="hidden" name="query" class="batch-query" value="<?php echo $this->escapeHtml(json_encode($this->params()->fromQuery())); ?>">
    </div>
</div>
<?php endif; ?>

<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th class="row-select">
                <?php if ($canViewBatchUpdate): ?>
                <input type="checkbox" class="select-all" aria-label="<?php echo $this->translate('Select all'); ?>">
                <?php endif; ?>
                <?php echo $this->translate('Record #'); ?>
            </th>
            <th><?php echo $this->translate('Owner'); ?></th>
            <th><?php echo $this->translate('Date created'); ?></th>
            <th><?php echo $this->translate('Needs review'); ?></th>
            <th><?php echo $this->translate('Needs work'); ?></th>
            <?php foreach ($dataset->fields() as $field): ?>
            <th><?php echo $field->name([
                'length' => 20,
                'trim_marker' => '<span style="color: LightGray;">...</span>',
            ]); ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($records as $record): ?>
        <?php
        $values = $record->values();
        $owner = $record->owner();
        ?>
        <tr>
            <td>
                <?php if ($canViewBatchUpdate): ?>
                <input type="checkbox" name="record_ids[]" value="<?php echo $item->id(); ?>" aria-label="<?php echo $this->translate('Select records'); ?>">
                <?php endif; ?>
                <?php echo number_format($record->id()); ?>
                <ul class="actions">
                    <?php if ($record->userIsAllowed('update')): ?>
                    <li><?php echo $record->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'title' => $this->translate('Edit'),
                    ]) ?></li>
                    <?php endif; ?>
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-content-url' => $record->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'data-sidebar-selector' => '#show-details',
                        'title' => $this->translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?php echo $owner ? $owner->link($owner->name()) : ''; ?></td>
            <td><?php echo $this->i18n()->dateFormat($record->created()); ?></td>
            <td><?php echo $record->needsReview() ? '✓' : ''; ?></td>
            <td><?php echo $record->needsWork() ? '✓' : ''; ?></td>
            <?php foreach ($dataset->fields() as $field): ?>
            <?php $value = $values[$field->id()] ?? null; ?>
            <?php if (null === $value): ?>
            <td><span style="color: LightGray;"><?php echo $this->translate('null'); ?></span></td>
            <?php else: ?>
            <td><?php echo $value->value([
                'length' => 100,
                'trim_marker' => '<span style="color: LightGray;">...</span>',
                'if_invalid_return' => sprintf('<span style="color: Red;">%s</span>', $this->translate('invalid')),
                'if_empty_return' => sprintf('<span style="color: LightGray;">%s</span>', $this->translate('empty')),
            ]); ?></td>
            <?php endif; ?>
            <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

</form>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<?php else: ?>
<div class="no-resources">
    <p><?php echo $this->translate('No records found.'); ?></p>
</div>
<?php endif; ?>

<div class="sidebar always-open">
    <button type="button" class="sidebar-drawer collapse" aria-label="<?php echo $this->translate('Collapse'); ?>"></button>
    <div class="meta-group">
        <h3><?php echo $this->translate('Lock action'); ?></h3>
        <select>
            <option>[No change]</option>
            <option>Unlock</option>
            <option>Lock to me</option>
            <option>Lock to transcriber...</option>
            <option>Lock to reviewer...</option>
            <option>Lock to admin...</option>
        </select>
    </div>
    <div class="meta-group">
        <h3><?php echo $this->translate('Review action'); ?></h3>
        <select>
            <option>[No change]</option>
            <option>Mark as approved</option>
            <option>Mark as not approved</option>
            <option>Mark as not reviewed</option>
        </select>
    </div>
    <div class="meta-group">
        <h3><?php echo $this->translate('Priority action'); ?></h3>
        <select>
            <option>[No change]</option>
            <option>Mark as prioritized</option>
            <option>Mark as not prioritized</option>
        </select>
    </div>
    <div class="meta-group">
        <h3><?php echo $this->translate('Transcriber notes'); ?></h3>
        <textarea rows="8"></textarea>
    </div>
    <div class="meta-group">
        <h3><?php echo $this->translate('Reviewer notes'); ?></h3>
        <textarea rows="8"></textarea>
    </div>
    <?php echo $this->partial('datascribe/admin/item/show-details'); ?>
</div>
