<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe record edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/admin.css', 'Datascribe'));
$this->headLink()->appendStylesheet('https://cdn.jsdelivr.net/npm/tablesaw@3.1.2/dist/tablesaw.css');
$this->headScript()->appendFile($this->assetUrl('js/admin.js', 'Datascribe'));
$this->headScript()->appendFile($this->assetUrl('js/admin/record-browse.js', 'Datascribe'));
$this->headScript()->appendFile($this->assetUrl('vendor/jquery-panzoom/jquery.panzoom.min.js', 'Datascribe'));
$this->headScript()->appendFile($this->assetUrl('vendor/featherlight/featherlight.min.js', 'Datascribe'));
$this->headScript()->appendFile($this->assetUrl('js/admin/media-viewer.js', 'Datascribe'));
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/tablesaw@3.1.2/dist/tablesaw.jquery.js');
$form->prepare();
?>
<?php echo $this->pageTitle($record->displayTitle(), 1, $this->translate('DataScribe: Record'), $this->translate('Edit')); ?>

<?php echo $this->partial('before-after-records', ['dataset' => $dataset, 'records' => $recordsBefore, 'beforeAfter' => $this->translate('Before')]); ?>

<div class="current-row">
<div class="media-viewer">
      <?php $media = $oItem->media(); ?>
      <?php $mediaCount = count($media); ?>
      <?php if (count($media) > 1): ?>
      <div class="media-select">
          <select name="active-media" id="active-media">
              <?php $i = 0; ?>
              <?php foreach ($media as $file): ?> 
              <option name="media-<?php echo $i; ?>" value="<?php echo $file->originalUrl(); ?>"><?php echo $file->displayTitle(); ?></option>
              <?php $i++; ?>
              <?php endforeach; ?>
          </select>
          <nav class="media pagination">
            <input type="number" min="1" max="<?php echo $mediaCount; ?>" aria-label="<?php echo $this->translate('Media'); ?>" name="active-media" value="1">
            <span class="media-count"><?php echo sprintf($this->translate('of %s'), $mediaCount); ?></span>
            <button type="button" aria-label="<?php echo $this->translate('Previous'); ?>" class="previous o-icon-prev button inactive" disabled="disabled"></button>
            <button type="button" aria-label="<?php echo $this->translate('Next'); ?>" class="next o-icon-next button"></button>
          </nav>
      </div>
      <?php endif; ?>
      <?php if ($mediaCount > 0): ?>
      <?php $primaryMedia = $oItem->primaryMedia(); ?>
      <div class="media-container">
        <div class="panzoom-container image">
            <div class="zoom-controls">
                <button class="zoom-in" aria-label="<?php echo $this->translate('Zoom in'); ?>" title="<?php echo $this->translate('Zoom in'); ?>"></button>
                <button class="zoom-out" aria-label="<?php echo $this->translate('Zoom out'); ?>" title="<?php echo $this->translate('Zoom out'); ?>"></button>
                <button class="rotate-right" aria-label="<?php echo $this->translate('Rotate right'); ?>" title="<?php echo $this->translate('Rotate right'); ?>"></button>
                <button class="rotate-left" aria-label="<?php echo $this->translate('Rotate left'); ?>" title="<?php echo $this->translate('Rotate left'); ?>"></button>
                <button class="reset"><?php echo $this->translate('Reset'); ?></button>
            </div>
            <div class="media-render">
              <img src="<?php echo $this->escapeHtml($primaryMedia->originalUrl()); ?>" title="<?php echo $primaryMedia->displayTitle(); ?>">
            </div>
        </div>
      </div>
      <?php endif; ?>
</div>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formElement($form->get('csrf')); ?>

<div id="page-actions">
    <?php echo $this->cancelButton(); ?>
    <a href="#" class="delete button"><?php echo $this->translate('Delete'); ?></a>
    <button><?php echo $this->translate('Save'); ?></button>
</div>

<?php foreach ($form->get('o-module-datascribe:value')->getFieldsets() as $fieldset): ?>
<fieldset>
    <?php echo sprintf('<legend>%s</legend>', $fieldset->getOption('datascribe_field_name')); ?>
    <?php if ($fieldDescription = $fieldset->getOption('datascribe_field_description')): ?>
    <?php echo sprintf('<p>%s</p>', $fieldDescription); ?>
    <?php endif; ?>
    <?php if ($fieldset->has('invalid_data')): ?>
    <?php echo $this->formRow($fieldset->get('invalid_data')); ?>
    <?php endif; ?>
    <?php echo $this->formCollection($fieldset->get('data'), false); ?>
    <?php echo $this->formRow($fieldset->get('is_missing')); ?>
    <?php echo $this->formRow($fieldset->get('is_illegible')); ?>
</fieldset>
<?php endforeach; ?>

<div class="sidebar always-open">
    <button type="button" class="sidebar-drawer collapse" aria-label="<?php echo $this->translate('Collapse'); ?>"></button>
    <h3><?php echo $this->translate('Record actions'); ?></h3>
    <?php if ($form->has('o-module-datascribe:needs_review')): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Needs review'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:needs_review')); ?></div>
    </div>
    <?php endif; ?>
    <?php if ($form->has('o-module-datascribe:needs_work')): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Needs work'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:needs_work')); ?></div>
    </div>
    <?php endif; ?>
    <?php if ($form->has('o-module-datascribe:transcriber_notes')): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Transcriber notes'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:transcriber_notes')); ?></div>
    </div>
    <?php endif; ?>
    <?php if ($form->has('o-module-datascribe:reviewer_notes')): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Reviewer notes'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:reviewer_notes')); ?></div>
    </div>
    <?php endif; ?>
    <?php echo $this->partial('show-details'); ?>
</div>

<?php echo $this->form()->closeTag(); ?>

</div>

<?php echo $this->partial('before-after-records', ['dataset' => $dataset, 'records' => $recordsAfter, 'beforeAfter' => $this->translate('After')]); ?>

<?php echo $this->deleteConfirm($record, 'record'); ?>
