<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe record edit');
$this->headLink()->appendStylesheet('https://cdn.jsdelivr.net/npm/tablesaw@3.1.2/dist/tablesaw.css');
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/tablesaw@3.1.2/dist/tablesaw.jquery.js');
$form->prepare();
?>

<?php echo $this->pageTitle($record->displayTitle(), 1, $this->translate('DataScribe: Record'), $this->translate('Edit')); ?>

<?php echo $this->partial('before-after-records', ['dataset' => $dataset, 'records' => $recordsBefore, 'beforeAfter' => $this->translate('Before')]); ?>

<div class="current-row horizontal">

<div class="row-controls">
    <button type="button" class="full-screen"><?php echo $this->translate('Focus mode'); ?></button>
    <div class="layout">
        <label><?php echo $this->translate('Layout'); ?></label>
        <button type="button" name="horizontal" class="horizontal active" aria-label="<?php echo $this->escapeHtml($this->translate('Horizontal view')); ?>" title="<?php echo $this->escapeHtml($this->translate('Horizontal view')); ?>" disabled=""></button>
        <button type="button" name="vertical" class="vertical" aria-label="<?php echo $this->escapeHtml($this->translate('Vertical view')); ?>" title="<?php echo $this->escapeHtml($this->translate('Vertical view')); ?>"></button>
    </div>
</div>

<?php echo $this->partial('media-viewer', ['oItem' => $oItem]); ?>

<?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formElement($form->get('csrf')); ?>
    
    <div id="page-actions">
        <?php echo $this->hyperlink($this->translate('Cancel'), $this->url('admin/datascribe-record', ['action' => 'browse'], true), ['class' => 'button']); ?>
        <a href="#" class="delete button"><?php echo $this->translate('Delete'); ?></a>
        <button><?php echo $this->translate('Save'); ?></button>
    </div>
    
    <?php foreach ($form->get('o-module-datascribe:value')->getFieldsets() as $fieldset): ?>
    <?php
    $field = $fieldset->getOption('datascribe_field');
    $value = $fieldset->getOption('datascribe_value');
    ?>
    <fieldset>
        <?php echo sprintf('<legend>%s</legend>', $field->name()); ?>
        <?php if ($fieldDescription = $field->description()): ?>
        <?php echo sprintf('<p>%s</p>', $fieldDescription); ?>
        <?php endif; ?>
        <?php if ($field->isRequired()): ?>
        <?php echo sprintf('<p class="warning">%s</p>', $this->translate('This field is required. The value will be marked as invalid if not completed.')); ?>
        <?php endif; ?>
        <?php if ($field->dataTypeIsUnknown()): ?>
        <?php echo sprintf('<p class="error">%s</p>', $this->translate('This field\'s data type is unknown. The value cannot be edited.')); ?>
        <?php elseif ($value && !$value->textIsValid()): ?>
        <?php echo sprintf('<p class="error">%s</p>', $this->translate('This value is invalid. Please correct it below and save this form.')); ?>
        <?php elseif ($value && $value->isInvalid()): ?>
        <?php echo sprintf('<p class="error">%s</p>', $this->translate('This value is marked as invalid but does not appear to be invalid. Either re-validate the dataset or save this form as-is.')); ?>
        <?php endif; ?>
        <?php if ($fieldset->has('invalid_value_text')): ?>
        <?php echo $this->formRow($fieldset->get('invalid_value_text')); ?>
        <?php endif; ?>
        <?php echo $this->formCollection($fieldset->get('data'), false); ?>
        <?php echo $this->formRow($fieldset->get('is_missing')); ?>
        <?php echo $this->formRow($fieldset->get('is_illegible')); ?>
    </fieldset>
    <?php endforeach; ?>
    
    <div class="sidebar always-open">
        <button type="button" class="sidebar-drawer collapse" aria-label="<?php echo $this->translate('Collapse'); ?>"></button>
        <h3><?php echo $this->translate('Record actions'); ?></h3>
        <?php if ($form->has('o-module-datascribe:needs_review')): ?>
        <div class="meta-group checkbox">
            <h4><?php echo $this->translate('Needs review'); ?></h4>
            <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:needs_review')); ?></div>
        </div>
        <?php endif; ?>
        <?php if ($form->has('o-module-datascribe:needs_work')): ?>
        <div class="meta-group checkbox">
            <h4><?php echo $this->translate('Needs work'); ?></h4>
            <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:needs_work')); ?></div>
        </div>
        <?php endif; ?>
        <?php if ($form->has('o-module-datascribe:transcriber_notes')): ?>
        <div class="meta-group">
            <h4><?php echo $this->translate('Transcriber notes'); ?></h4>
            <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:transcriber_notes')); ?></div>
        </div>
        <?php endif; ?>
        <?php if ($form->has('o-module-datascribe:reviewer_notes')): ?>
        <div class="meta-group">
            <h4><?php echo $this->translate('Reviewer notes'); ?></h4>
            <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:reviewer_notes')); ?></div>
        </div>
        <?php endif; ?>
        <?php echo $this->partial('show-details'); ?>
    </div>

<?php echo $this->form()->closeTag(); ?>
</div>

<?php echo $this->partial('before-after-records', ['dataset' => $dataset, 'records' => $recordsAfter, 'beforeAfter' => $this->translate('After')]); ?>

<?php echo $this->deleteConfirm($record, 'record'); ?>
