<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe record edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/admin.css', 'Datascribe'));
$this->headLink()->appendStylesheet('https://cdn.jsdelivr.net/npm/tablesaw@3.1.2/dist/tablesaw.css');
$this->headScript()->appendFile($this->assetUrl('js/admin.js', 'Datascribe'));
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/tablesaw@3.1.2/dist/tablesaw.jquery.js');
$form->prepare();
$primaryValue = $record->primaryValue();
$primaryValueText = $primaryValue
        ? $primaryValue->value([
            'length' => 25,
            'if_invalid_return' => sprintf('[%s]', $this->translate('[Record]')),
            'if_empty_return' => sprintf('[%s]', $this->translate('[Record]')),
        ])
        : $this->translate('[Record]');
?>
<?php echo $this->pageTitle($primaryValueText, 1, $this->translate('DataScribe: Record'), $this->translate('Edit')); ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formElement($form->get('csrf')); ?>
<div id="page-actions">
    <?php echo $this->cancelButton(); ?>
    <a href="#" class="delete button"><?php echo $this->translate('Delete'); ?></a>
    <button><?php echo $this->translate('Save'); ?></button>
</div>

<?php foreach ($form->get('o-module-datascribe:value')->getFieldsets() as $fieldset): ?>
<fieldset>
    <?php echo sprintf('<legend>%s</legend>', $fieldset->getOption('datascribe_field_name')); ?>
    <?php echo sprintf('<p>%s</p>', $fieldset->getOption('datascribe_field_description')); ?>
    <?php if ($fieldset->has('invalid_data')): ?>
    <?php echo $this->formRow($fieldset->get('invalid_data')); ?>
    <?php endif; ?>
    <?php echo $this->formCollection($fieldset->get('data'), false); ?>
    <?php echo $this->formRow($fieldset->get('is_missing')); ?>
    <?php echo $this->formRow($fieldset->get('is_illegible')); ?>
</fieldset>
<?php endforeach; ?>

<div class="sidebar always-open">
    <button type="button" class="sidebar-drawer collapse" aria-label="<?php echo $this->translate('Collapse'); ?>"></button>
    <h3><?php echo $this->translate('Record flags'); ?></h3>
    <div class="meta-group">
        <h4><?php echo $this->translate('Needs review'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:needs_review')); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Needs work'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:needs_work')); ?></div>
    </div>
    <h3><?php echo $this->translate('Record notes'); ?></h3>
    <div class="meta-group">
        <h4><?php echo $this->translate('Transcriber notes'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:transcriber_notes')); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Reviewer notes'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:reviewer_notes')); ?></div>
    </div>
    <?php echo $this->partial('show-details'); ?>
</div>

<?php echo $this->form()->closeTag(); ?>

<?php echo $this->deleteConfirm($record, 'record'); ?>
