<div id="sidebar-delete-selected" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <div class="sidebar-content">
        <div id="sidebar-confirm">
            <h3><?php echo $this->translate('Delete records'); ?></h3>
            <p><?php echo $this->translate('Are you sure you would like to delete the selected records?'); ?></p>
            <p class="error"><?php echo sprintf(
                $this->translate('%1$s: this action will permanently delete %2$s records and cannot be undone.'),
                sprintf('<strong>%s</strong>', $this->translate('Warning')),
                '<strong><span id="delete-selected-count"></span></strong>'
            ); ?></p>
            <?php echo $this->form($this->formDeleteSelected); ?>
        </div>
    </div>
</div>

<div id="sidebar-delete-all" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <div class="sidebar-content">
        <div id="sidebar-confirm">
            <h3><?php echo $this->translate('Delete records'); ?></h3>
            <p><?php echo $this->translate('Are you sure you would like to delete all records on all pages of this result?'); ?></p>
            <p class="error"><?php echo sprintf(
                $this->translate('%1$s: this action will permanently delete %2$s records and cannot be undone.'),
                sprintf('<strong>%s</strong>', $this->translate('Warning')),
                sprintf('<strong>%s</strong>', number_format($this->pagination()->getPaginator()->getTotalCount()))
            ); ?></p>
            <label><input type="checkbox" name="confirm-delete-all-check"> <?php echo $this->translate('Are you sure?'); ?></label>
            <?php echo $this->form($this->formDeleteAll); ?>
        </div>
    </div>
</div>
