<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe record show');
$values = $record->values();
?>

<?php echo $this->pageTitle($record->displayTitle(), 1, $this->translate('DataScribe: Record'), $this->translate('Show')); ?>

<?php echo $this->datascribe()->breadcrumbs(); ?>

<dl>
    <?php foreach ($dataset->fields() as $field): ?>
    <?php $value = $values[$field->id()] ?? null; ?>
    <dt><?php echo $field->name(); ?></dt>
    <?php if ($field->dataTypeIsUnknown()): ?>
    <dd><span style="color: #ffcccc;"><?php echo $this->translate('unknown'); ?></span></dd>
    <?php elseif ($field->isRequired() && (null === $value)): ?>
    <dd><span style="color: #ffcccc;"><?php echo $this->translate('invalid'); ?></span></dd>
    <?php elseif (null === $value): ?>
    <dd><span style="color: #e6e6e6;"><?php echo $this->translate('null'); ?></span></dd>
    <?php else: ?>
    <dd>
        <?php echo $value->displayText([
            'if_invalid_return' => sprintf('<span style="color: #ffcccc;">%s</span>', $this->translate('invalid')),
            'if_empty_return' => sprintf('<span style="color: #e6e6e6;">%s</span>', $this->translate('empty')),
            'if_null_return' => sprintf('<span style="color: #e6e6e6;">%s</span>', $this->translate('null')),
            'if_unknown_return' => sprintf('<span style="color: #ffcccc;">%s</span>', $this->translate('unknown')),
        ]); ?>
    </dd>
    <?php endif; ?>
    <?php endforeach; ?>
</dl>

<div class="sidebar always-open">
    <?php echo $this->partial('show-details'); ?>
</div>
