<div class="no-resources">
    <?php if ($this->userIsAllowed('Datascribe\Api\Adapter\DatascribeDatasetAdapter', 'create')): ?>
    <p><?php echo sprintf(
        $this->translate('This dataset has no form. %s'),
        $this->hyperlink($this->translate('Build the form.'), $this->url('admin/datascribe-dataset-id', ['action' => 'edit', 'project-id' => $project->id(), 'dataset-id' => $dataset->id()], ['fragment' => 'form-builder']))
    ); ?></p>
    <?php else: ?>
    <p><?php echo $this->translate('This dataset has no form.'); ?></p>
    <?php endif; ?>
</div>
