<div class="row-controls">
    <button type="button" class="full-screen"><?php echo $this->translate('Focus mode'); ?></button>
    <div class="layout">
        <label><?php echo $this->translate('Layout'); ?></label>
        <button type="button" name="horizontal" class="horizontal active" aria-label="<?php echo $this->escapeHtml($this->translate('Horizontal view')); ?>" title="<?php echo $this->escapeHtml($this->translate('Horizontal view')); ?>" disabled=""></button>
        <button type="button" name="vertical" class="vertical" aria-label="<?php echo $this->escapeHtml($this->translate('Vertical view')); ?>" title="<?php echo $this->escapeHtml($this->translate('Vertical view')); ?>"></button>
    </div>
    <?php if ($dataset->guidelines()): ?>
    <button type="button" class="open-guidelines"><?php echo $this->translate('Guidelines'); ?></button>
    <?php endif; ?>
</div>
