<div class="sidebar always-open">
    <button type="button" class="sidebar-drawer collapse" aria-label="<?php echo $this->translate('Collapse'); ?>"></button>
    <div class="meta-group">
        <input type="submit" name="submit-save-progress"  class="button" value="<?php echo $this->escapeHtml($this->translate('Save progress')); ?>">
        <?php if ('edit' === $action): ?>
        <?php $lastSaved = $record->modified() ?? $record->created(); ?>
        <div class="last-saved-timestamp"><?php echo sprintf($this->translate('Last saved: %s on %s'), $lastSaved->format('g:i:sa'), $lastSaved->format('M j, Y')); ?></div>
        <?php endif; ?>
    </div>
    <h3><?php echo $this->translate('Record actions'); ?></h3>
    <?php if ($form->has('o-module-datascribe:needs_review')): ?>
    <div class="meta-group checkbox">
        <h4><?php echo $this->translate('Needs review'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:needs_review')); ?></div>
    </div>
    <?php endif; ?>
    <?php if ($form->has('o-module-datascribe:needs_work')): ?>
    <div class="meta-group checkbox">
        <h4><?php echo $this->translate('Needs work'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:needs_work')); ?></div>
    </div>
    <?php endif; ?>
    <?php if ($form->has('position_change_record_id')): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Position'); ?></h4>
        <div class="value">
            <?php echo $this->formElement($form->get('position_change_direction')); ?>
            <?php echo $this->formElement($form->get('position_change_record_id')); ?>
        </div>
    </div>
    <?php endif; ?>
    <?php if ($form->has('o-module-datascribe:transcriber_notes')): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Transcriber notes'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:transcriber_notes')); ?></div>
    </div>
    <?php endif; ?>
    <?php if ($form->has('o-module-datascribe:reviewer_notes')): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Reviewer notes'); ?></h4>
        <div class="value"><?php echo $this->formElement($form->get('o-module-datascribe:reviewer_notes')); ?></div>
    </div>
    <?php endif; ?>
    <?php if ('edit' === $action): ?>
    <?php echo $this->partial('show-details'); ?>
    <?php endif; ?>
</div>
