<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe dashboard');
?>

<?php echo $this->pageTitle($this->translate('Dashboard'), 1, $this->translate('DataScribe')); ?>

<div id="page-actions">
    <div id="page-action-menu">
        <a href="#" class="expand button" aria-label="<?php echo $this->translate('Expand'); ?>"><?php echo $this->translate('Actions'); ?></a>
        <ul class="collapsible">
            <li><?php echo $this->hyperlink($this->translate('Browse projects'), $this->url('admin/datascribe-project')); ?></li>
            <?php if ($this->userIsAllowed('Datascribe\Api\Adapter\DatascribeProjectAdapter', 'create')): ?>
            <li><?php echo $this->hyperlink($this->translate('Add new project'), $this->url('admin/datascribe-project', ['action' => 'add'])); ?></li>
            <?php endif; ?>
        </ul>
    </div>
</div>
