<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe dashboard');
?>

<?php echo $this->pageTitle($this->translate('Dashboard'), 1, $this->translate('DataScribe')); ?>

<div id="page-actions">
    <div id="page-action-menu">
        <a href="#" class="expand button" aria-label="<?php echo $this->translate('Expand'); ?>"><?php echo $this->translate('Actions'); ?></a>
        <ul class="collapsible">
            <li><?php echo $this->hyperlink($this->translate('Browse projects'), $this->url('admin/datascribe-project')); ?></li>
            <?php if ($this->userIsAllowed('Datascribe\Api\Adapter\DatascribeProjectAdapter', 'create')): ?>
            <li><?php echo $this->hyperlink($this->translate('Add new project'), $this->url('admin/datascribe-project', ['action' => 'add'])); ?></li>
            <?php endif; ?>
        </ul>
    </div>
</div>

<h2><?php echo $this->translate('Welcome to DataScribe'); ?></h2>
<ul>
    <li><?php echo $this->hyperlink($this->translate('Browse projects'), $this->url('admin/datascribe-project')); ?></li>
    <?php if ($this->userIsAllowed('Datascribe\Api\Adapter\DatascribeProjectAdapter', 'create')): ?>
    <li><?php echo $this->hyperlink($this->translate('Add new project'), $this->url('admin/datascribe-project', ['action' => 'add'])); ?></li>
    <?php endif; ?>
</ul>

<?php if ($myProjects): ?>
<h2><?php echo $this->translate('My projects'); ?></h2>
<ul>
    <?php foreach ($myProjects as $myProject): ?>
    <li><?php echo sprintf('%s (%s)', $myProject['project']->link($myProject['project']->name()), implode('/', $myProject['roles'])); ?></li>
    <ul>
        <?php foreach ($myProject['datasets'] as $myDataset): ?>
        <li><?php echo $myDataset->link($myDataset->name()) ?></li>
        <ul>
            <li><?php echo $this->hyperlink(
                $this->translate('All unlocked and new items'),
                $this->url(
                    'admin/datascribe-item',
                    ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                    ['query' => ['limit' => 25, 'sort_by' => 'created', 'sort_order' => 'asc', 'all_unlocked_and_in_progress' => true]]
                )
            ); ?></li>
            <li><?php echo $this->hyperlink(
                $this->translate('All unlocked and in progress items'),
                $this->url(
                    'admin/datascribe-item',
                    ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                    ['query' => ['limit' => 25, 'sort_by' => 'created', 'sort_order' => 'asc', 'all_unlocked_and_new' => true]]
                )
            ); ?></li>
            <li><?php echo $this->hyperlink(
                $this->translate('My new items'),
                $this->url(
                    'admin/datascribe-item',
                    ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                    ['query' => ['limit' => 25, 'sort_by' => 'locked', 'sort_order' => 'asc', 'my_new' => true]]
                )
            ); ?></li>
            <li><?php echo $this->hyperlink(
                $this->translate('My in progress items'),
                $this->url(
                    'admin/datascribe-item',
                    ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                    ['query' => ['limit' => 25, 'sort_by' => 'locked', 'sort_order' => 'asc', 'my_in_progress' => true]]
                )
            ); ?></li>
            <li><?php echo $this->hyperlink(
                $this->translate('My items that are not approved'),
                $this->url(
                    'admin/datascribe-item',
                    ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                    ['query' => ['limit' => 25, 'sort_by' => 'reviewed', 'sort_order' => 'asc', 'my_not_approved' => true]]
                )
            ); ?></li>
            <?php if ($myDataset->userIsAllowed('datascribe_view_item_batch_update')): ?>
            <li><?php echo $this->hyperlink(
                $this->translate('Items I reviewed that need re-review'),
                $this->url(
                    'admin/datascribe-item',
                    ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                    ['query' => ['limit' => 25, 'sort_by' => 'submitted', 'sort_order' => 'asc', 'my_reviewed_and_need_review' => true]]
                )
            ); ?></li>
            <li><?php echo $this->hyperlink(
                $this->translate('All items that need review'),
                $this->url(
                    'admin/datascribe-item',
                    ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                    ['query' => ['limit' => 25, 'sort_by' => 'submitted', 'sort_order' => 'asc', 'all_need_review' => true]]
                )
            ); ?></li>
            <?php endif; ?>
        </ul>
        <?php endforeach; ?>
    </ul>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
