<?php
$this->htmlElement('body')->appendAttribute('class', 'datascribe dashboard');
?>

<?php echo $this->pageTitle($this->translate('Dashboard'), 1, $this->translate('DataScribe')); ?>

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Browse projects'), $this->url('admin/datascribe-project'), ['class' => 'button']); ?>
    <?php echo $this->hyperlink($this->translate('Add new project'), $this->url('admin/datascribe-project', ['action' => 'add']), ['class' => 'button']); ?>
</div>

<p class="welcome"><?php echo $this->translate('Welcome to DataScribe.'); ?></p>

<?php if ($recentProjects): ?>
<div class="recent project browse">
    <h2><?php echo $this->translate('Recently modified projects'); ?></h2>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $this->translate('Project'); ?></th>
                <th><?php echo $this->translate('Modified'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($recentProjects as $project): ?>
        <?php $createdBy = $project->createdBy(); ?>
            <tr>
                <td>
                    <?php echo $project->link($project->name()); ?>
                    <?php if (!$project->isPublic()): ?>
                        <span class="o-icon-private" aria-label="<?php echo $this->translate('Private'); ?>"></span>
                    <?php endif; ?>
                </td>
                <td><?php echo $this->i18n()->dateFormat($project->modified()); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->hyperlink($this->translate('View all projects'), $this->url('admin/datascribe-project'), ['class' => 'view-all']); ?>
</div>
<?php endif; ?>

<?php if ($myProjects): ?>
<div class="my-projects">
    <h2><?php echo $this->translate('My projects'); ?></h2>
    <ul class="user-projects">
        <?php foreach ($myProjects as $myProject): ?>
        <li><?php echo sprintf('%s (%s)', $myProject['project']->link($myProject['project']->name()), implode('/', $myProject['roles'])); ?>
          <ul>
              <?php foreach ($myProject['datasets'] as $myDataset): ?>
              <li><?php echo $myDataset->link($myDataset->name()) ?>
                  <ul>
                      <li><?php echo $this->hyperlink(
                          $this->translate('All unlocked and new items'),
                          $this->url(
                              'admin/datascribe-item',
                              ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                              ['query' => ['limit' => 25, 'sort_by' => 'created', 'sort_order' => 'asc', 'all_unlocked_and_in_progress' => true]]
                          )
                      ); ?></li>
                      <li><?php echo $this->hyperlink(
                          $this->translate('All unlocked and in progress items'),
                          $this->url(
                              'admin/datascribe-item',
                              ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                              ['query' => ['limit' => 25, 'sort_by' => 'created', 'sort_order' => 'asc', 'all_unlocked_and_new' => true]]
                          )
                      ); ?></li>
                      <li><?php echo $this->hyperlink(
                          $this->translate('My new items'),
                          $this->url(
                              'admin/datascribe-item',
                              ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                              ['query' => ['limit' => 25, 'sort_by' => 'locked', 'sort_order' => 'asc', 'my_new' => true]]
                          )
                      ); ?></li>
                      <li><?php echo $this->hyperlink(
                          $this->translate('My in progress items'),
                          $this->url(
                              'admin/datascribe-item',
                              ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                              ['query' => ['limit' => 25, 'sort_by' => 'locked', 'sort_order' => 'asc', 'my_in_progress' => true]]
                          )
                      ); ?></li>
                      <li><?php echo $this->hyperlink(
                          $this->translate('My items that are not approved'),
                          $this->url(
                              'admin/datascribe-item',
                              ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                              ['query' => ['limit' => 25, 'sort_by' => 'reviewed', 'sort_order' => 'asc', 'my_not_approved' => true]]
                          )
                      ); ?></li>
                      <?php if ($myDataset->userIsAllowed('datascribe_view_item_batch_update')): ?>
                      <li><?php echo $this->hyperlink(
                          $this->translate('Items I reviewed that need re-review'),
                          $this->url(
                              'admin/datascribe-item',
                              ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                              ['query' => ['limit' => 25, 'sort_by' => 'submitted', 'sort_order' => 'asc', 'my_reviewed_and_need_review' => true]]
                          )
                      ); ?></li>
                      <li><?php echo $this->hyperlink(
                          $this->translate('All items that need review'),
                          $this->url(
                              'admin/datascribe-item',
                              ['project-id' => $myProject['project']->id(), 'dataset-id' => $myDataset->id()],
                              ['query' => ['limit' => 25, 'sort_by' => 'submitted', 'sort_order' => 'asc', 'all_need_review' => true]]
                          )
                      ); ?></li>
                      <?php endif; ?>
                  </ul>
              </li>
              <?php endforeach; ?>
          </ul>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
